---
output:
  pdf_document: default
  html_document: default
---
# 1 Introduction

Beaked whales (family Ziphiidae) are a group of deep-diving cetaceans that rely on sound to forage, navigate, and communicate [@macleod_review_2006; @johnson_beaked_2004; @aguilar_de_soto_no_2012].  Multiple mass strandings of beaked whales have been associated with high-intensity anthropogenic sound sources.  These acute events have motivated research into whether and how beaked whales respond to different types and intensities of anthropogenic noise [@cox_understanding_2006].

Anthropogenic sound can disrupt the patterned foraging dive cycles of beaked whales [@falcone_diving_2017], potentially leading to cumulative sublethal impacts resulting from reduced foraging opportunities [@new_using_2013], or to symptoms similar to decompression sickness that can lead to injury or death [@bernaldo_de_quiros_advances_2019].  For example, research on Blainville's beaked whales \textit{Mesoplodon densirostris} on a US Navy range in the Bahamas has shown that animals may stop foraging and/or move away from naval sonar sources [@tyack_beaked_2011; @joyce_behavioral_2019].

Naval sonar can be broadcast from various platforms, including vessels, helicopters, buoys, submarines, and torpedoes [@harris_changes_2019; @u.s._department_of_the_navy_final_2018].  Most research has focused on the impacts of mid-frequency active sonar (MFAS) broadcast from naval vessels.  Separately, researchers have shown that, in the absence of MFAS, beaked whales may alter their behavior in response to vessel noise [@aguilar_de_soto_does_2006; @pirotta_vessel_2012].  

The US Navy is interested in quantifying the effects of sonar on beaked whales for the purpose of risk assessments and permitting associated with training activities [e.g., @navy2017criteria].  There are different experimental and analytical ways of quantifying responses to sonar.  Here, we focus on analyses of data from cabled hydrophone arrays.

For example, McCarthy et al. [-@mccarthy_changes_2011] used data from the cabled hydrophone array at the US Navy's Atlantic Undersea Test and Evaluation Center (AUTEC) in the Bahamas collected before, during, and after naval training exercises involving MFAS.  The authors used separate generalized additive models (GAMs) for each period, and modelled the acoustic detection of groups of Blainville's beaked whales (group vocal periods; GVPs) as a function of location on the range and time.  They found that the number of GVPs was lower during the exercises than before or after.  

Building on this work, Moretti et al. [-@moretti_risk_2014] used a GAM to model the presence of acoustic detections of groups of Blainville’s beaked whales on the AUTEC range as a smooth function of MFAS received level. They then compared the expected probability of detecting animals when no sonar was present to the expected probability of detecting animals across sonar received levels to estimate the probability of disturbance. They found that the probability of detecting groups of Blainville's beaked whales was reduced by 50\% at 150 dB re 1$\mu$Pa, which they interpreted as a 50\% probability of disturbance. 

Our primary objective was to replicate the effort of Moretti et al. [-@moretti_risk_2014] with the same species on a different US Navy training range in a different oceanic environment. Unlike AUTEC, which occurs in a deep isolated basin surrounded by steep slopes, the Pacific Missile Range Facility (PMRF) range in Hawaii is located on the side of an ancient volcano, with a steep slope down to the deep ocean floor. Density of Blainville's beaked whales at PMRF is lower and more variable than at AUTEC, so we wanted to explicitly account for differences in underlying beaked whale presence across the range.

An additional objective was to isolate the effect of general training activity from the effect of MFAS, so that beaked whale response to MFAS could be quantified relative to pre-training baseline periods and to periods when general training activities were present on the range.

We used a spatially referenced dataset of Blainville's beaked whale foraging dives recorded at the PMRF off the island of Kauai, Hawaii (Fig. 1).  Acoustic detections of Blainville's beaked whales were collected via a cabled hydrophone array at PMRF before and during training exercises involving MFAS broadcast from navy ships.  Previous work in this region has shown that Blainville's beaked whales are present year-round at this site, prefer slope habitats, and that acoustic detections decrease during multi-day training events involving MFAS [@henderson_occurrence_2016; @manzano-roth_impacts_2016].  

A series of three linked models were fitted.  The first was fitted to data collected before the training exercises began in order to estimate the underlying spatial distribution of acoustic detections.  The expected values from this model were used as offsets in the second model, which was fitted to data collected when training exercises were ongoing by no MFAS was broadcast.  The expected values from this second model were then used as offsets in the third model, which was fitted to data collected when training exercises that did use MFAS were ongoing.  Uncertainty was propagated through all models using posterior simulation.  With this set of model results, we quantified the expected decrease in detection of GVPs across increasing sonar received levels relative to both the pre-training baseline period and the period when training activities were ongoing but no MFAS was present. 
