---
output:
  pdf_document: default
  html_document: default
---

# Discussion

We used a series of three linked models to quantify the response of Blainville's beaked whales to naval training exercises involving MFAS: the first model was fitted to pre-exercise baseline data, the second was fitted to data collected when naval training exercises were ongoing but no MFAS was present, and the third model was fitted to data collected during naval training exercises that used MFAS. We found that the probability of acoustic detections of Blainville's beaked whales decreased when both naval training exercises and naval training exercises using MFAS were present (Fig. \@ref(fig:deltaships) and \@ref(fig:deltabaseline)).

The methods presented here are spatially explicit and account for the spatial confounding of animal distribution and naval training activity. The data used in this study are from an undesigned experiment, where the spatial intensity of the treatments (naval activity and MFAS) were not applied randomly with respect to either the study area or Blainville's beaked whale presence. We did not want the spatial distribution of training exercises and MFAS to influence our understanding of the baseline spatial distribution of Blainville's beaked whales. Due to the spatial confounding of animal distribution and naval training activity at PMRF, fitting a single model to all of the data would lead to underestimating the impact of sonar, since changes in distribution due to MFAS could be explained as spatial changes by the MRF (Appendix S3). Our three-stage modelling approach addresses this issue while propagating uncertainty between the models. To our knowledge, this is a novel application of GAMs.

The analytical approach outlined in this article could be applied to other species, regions, and types of disturbance where experimental design is not possible. The use of Markov random fields for the spatial term is useful for cases where exact distance data are not available, avoiding the use of continuous smoothers when true location data are not available. Shape-constrained smoothing is also well-suited to the kind of data we modelled here -- ensuring that values can only stay constant or decrease over time (or any other covariate). Finally, the use of a multi-stage posterior sampling scheme extends to any situation where multiple models are fitted and the results of one part feed into another. Simulation-based approaches such as these bypass the need to derive (often complex) mathematical expressions (or shortcut them by assuming independence).

The expected change in the probability of a GVP when naval training was present and when MFAS was present included wide CIs (Figs. 4 and 5) with upper bounds (97.5\% quantile) approaching a 100\% reduction in expected $P(\text{GVP})$ across received levels. This is likely due to the relatively small number of GVPs detected overall: GVPs were detected in only 1.2\% of half-hour periods in the dataset. GVPs were detected in 0.7\% of periods (n = 323) when naval activity was present, and 0.2\% (n = 48) when MFAS was present. The small number of GVPs when MFAS was present -- and therefore sparse coverage of data points across the range of received levels -- makes it difficult to estimate the effect of MFAS received level precisely. Additional data -- particularly at relatively low source levels, where uncertainty is greatest -- may reduce uncertainty in the expected probability of GVPs across different source levels. It is also possible that contextual factors that we did not include in this analysis, such as distance to sound source [@deruiter_first_2013-1; @falcone_diving_2017], may provide additional explanatory power and reduce uncertainty. It is also possible that the observed uncertainty reflects true individual variation in response due to variables like age and sex [see @harris_marine_2018 section 2.2 for a review of relevant publications].

In a regulatory context, a dose-response function as presented in Figs. 4 and 5 is often interpreted as representing the proportion of a population that responds (vertical axis) to a given received level (horizontal axis) [@tyack_using_2019]. However, the metric used in this study -- the change in the probability of detecting a GVP within a 30-min period -- may not directly correspond to the proportion of the population that is affected. It may instead reflect a change in the proportion of time that all individuals in the population spent foraging. These two interpretations have different implications for understanding sub-lethal impacts of MFAS. In the former interpretation, given exposure to a certain received level, some of the population is affected and some of the population is not. In the latter, the entire exposed population is affected. With our data, we cannot distinguish between these possible scenarios.

Blainville's beaked whales occur in multiple ocean basins and have been studied on U.S. Navy training ranges in both the Atlantic (AUTEC) and the Pacific (PMRF) Oceans. The AUTEC range is located in a deep basin bounded to the south, east, and west by shallow waters and with maximum depths of 2,000 m. In contrast, the PMRF occurs across a steep slope and into deep water, over 5,000 m in depth. Although the environments at PMRF and AUTEC are different, the foraging dive behavior of Blainville’s beaked whales is similar at AUTEC and PMRF: dives occur in waters over steep slopes with gradients ranging from 3-23\%, although dives occur in deeper waters [2,000-3,000 m, @henderson_occurrence_2016] at PMRF that at AUTEC [500-1,300 m, @macleod_habitat_2005; @hazen_relationship_2011]. Resident Blainville’s beaked whales off the island of Hawaii also occur in slightly shallower waters than at PMRF, from 980-1,410 m [@baird_diel_2008; @baird_short_2011]. Therefore it is likely the location of the mesopelagic scattering layer along the slope that drives the location of Blainville’s beaked whales rather than the bathymetric depth; this is supported by the fact that dive depths are similar across areas, occurring on average down to 1,050-1,150 m for 46-60 min [@baird_diel_2008; @schorr_movements_2009; @joyce_physiological_2017]. Documented responses to MFAS activity are comparable at both ranges, with individuals and groups moving to the periphery of the range or off the range and returning 2-4 days after the cessation of the sonar [@mccarthy_changes_2011; @manzano-roth_impacts_2016; @joyce_behavioral_2019]. 

In comparison to the risk function developed by Moretti et al. [-@moretti_risk_2014] for Blainville's beaked whales at AUTEC, our risk function for PMRF predicts a more intense response to naval sonar. This may be because Moretti et al. were not able to explicitly account for the effects of naval training activities that did not include MFAS. Their baseline period consisted of 19 hours of data before the onset of MFAS; as at PMRF, it is likely that training activities during this period included sound sources other than MFAS. Therefore, their risk function is probably more analogous to our expected change in the probability of a detection when MFAS is present relative to when naval training activity was present (Fig. \@ref(fig:deltaships)). Future research will investigate the specific causes of changes in the probability of detecting GVPs before the onset of MFAS. The reduction in detection of foraging dives could be a response to general Naval training activity on the range, or to specific sound sources that have not previously been studied. Alternatively, it is possible that Blainville's beaked whales are semi-resident on the range and have become habituated to SCC activity; they may move off the range in anticipation of MFAS. 
Resident animals that are frequently exposed to training activity and transient animals that only encounter MFAS occasionally are likely to respond differently to sonar. It is not known how resident the Blainville’s beaked whales are at PMRF, and there may be offshore animals as well found on the northern hydrophones. 

The similarities in Blainville’s beaked whale behavioral responses to Navy training activity across different ranges and environments at similar received levels may indicate the intrinsic nature of the response. The findings presented here and in Moretti et al. [-@moretti_risk_2014] may be applicable to other species and regions, though species-specific dive behaviors and regional differences in oceanography likely modulate the impact of MFAS. Conducting a similar analysis of Cuvier’s beaked whale responses at the Southern California Anti-Submarine Warfare Range (SOAR) would further support this assessment; existing findings already demonstrate that Cuvier’s respond in a similar manner by reducing their foraging dives and moving away from the ensonified area [@falcone_diving_2017; @deruiter_first_2013-1]. 



