# S1: Uncertainty estimation details {.unlisted .unnumbered}

We used posterior simulation to propagate uncertainty through $\texttt{M1}$, $\texttt{M2}$, and $\texttt{M3}$ Each model was fitted via restricted maximum likelihood (REML), so the resulting estimates were empirical Bayes estimates. In this case we generated 5,000 samples from the (approximately multivariate normal) posterior of the model parameters. We  generated a sample of the model parameters, $\boldsymbol{\beta}^* \sim \text{MVN}(\hat{\boldsymbol{\beta}}, \textbf{V}_{\hat{\boldsymbol{\beta}}})$, where $\hat{\boldsymbol{\beta}}$ is the estimate of the model coefficients and $\textbf{V}_{\hat{\boldsymbol{\beta}}}$ is the posterior covariance matrix. Here the $\boldsymbol{\beta}$ for each model included the coefficients for the smooth terms in the model and fixed effects (e.g., intercept) if present. We then used the matrix that maps the model parameters to the predictions on the linear predictor scale ($\mathbf{X}_p$; Wood et al. 2017; section 7.2.6), along with the inverse link function, to generate predictions for each posterior sample. Denoting the vector of predictions $\boldsymbol{\mu}^*$, we calculate as follows:
\begin{equation*}
        \boldsymbol{\mu}^* = g^{-1}(\boldsymbol{\eta}^*) = g^{-1}(\mathbf{X}_p\boldsymbol{\beta}^*+\boldsymbol{\xi}),
\end{equation*}
where $g$ was the link function, $\boldsymbol{\eta}^*$ was the linear predictor and $\boldsymbol{\xi}$ was any offset used by this prediction. Variance estimates can be obtained by taking the empirical variance of the resulting predictions (Wood et al. 2017; section 7.2.6). The prediction grid contained all possible combinations of covariates within the realized covariate space; i.e., each hydrophone for each SCC with associated location, hydrophone depth, and area of the tessellation tile, presence/absence of naval activity, and, if naval activity was present, then either sonar absence or sonar received level between 35 and 190 dB in intervals of 5 dB.  This procedure was repeated for each model, with refitting to updated offsets from the previous model.

An algorithm for calculating the variance from our multi-stage approach is as follows. First define $N_b$ as the number of samples to take ($N_b$=1000 here), let $\mathbf{X}_{p,\texttt{M}j}$ for $j=1,2,3$ be the matrix that maps coefficients to the predictions for model $\texttt{M}j$. For $N_b$ times:
\begin{enumerate}
    \item Draw a sample from the posterior of $\texttt{M1}$:  $\tilde{\boldsymbol{\beta}}_\texttt{M1}\sim\text{MVN}(\hat{\boldsymbol{\beta}}_\texttt{M1}, \mathbf{V}_\texttt{M1})$.
    \item Calculate a new offset for $\texttt{M2}$, $\tilde{\boldsymbol{\xi}}_{\texttt{M1}} = \mathbf{X}_{p,\texttt{M1}} \tilde{\boldsymbol{\beta}}_\texttt{M1} + \log_e \mathbf{A}$.
    \item Refit $\texttt{M2}$ with $\tilde{\boldsymbol{\xi}}_{\texttt{M1}}$ as the offset, to obtain $\texttt{M2}^\prime$.
    \item Draw a sample from the posterior of $\texttt{M2}^\prime$:  $\tilde{\boldsymbol{\beta}}_{\texttt{M2}^\prime} \sim\text{MVN}(\hat{\boldsymbol{\beta}}_{\texttt{M2}^\prime}, \mathbf{V}_{\texttt{M2}^\prime})$
    \item Calculate a new offset for $\texttt{M3}$, $\tilde{\boldsymbol{\xi}}_{\texttt{M2}} = \mathbf{X}_{p,\texttt{M2}} \tilde{\boldsymbol{\beta}}_\texttt{M2}^\prime + \tilde{\boldsymbol{\xi}}_{\texttt{M1}}$ (predictions for the sonar data locations for $\texttt{M2}^\prime$).
    \item Refit $\texttt{M3}$ with offset $\tilde{\boldsymbol{\xi}}_{\texttt{M2}}$ to obtain $\texttt{M3}^\prime$.
    \item Predict $\boldsymbol{\mu}_{\texttt{M1}^\prime}$, $\boldsymbol{\mu}_{\texttt{M2}^\prime}$, and $\boldsymbol{\mu}_{\texttt{M3}^\prime}$ over prediction grid and store them.
\end{enumerate}

We then calculated summary statistics (means and variances) of the $N_b$ values of $\boldsymbol{\mu}_{\texttt{M1}^\prime}$, $\boldsymbol{\mu}_{\texttt{M2}^\prime}$, and $\boldsymbol{\mu}_{\texttt{M3}^\prime}$ we generated. The empirical variance of the $N_b$ values of $\boldsymbol{\mu}_{\texttt{M3}^\prime}$ gave the uncertainty, incorporating components from all three models. We took appropriate pointwise quantiles (e.g., 2.5$^\text{th}$ and 97.5$^\text{th}$ for a 95% interval) to form confidence bands for the functional relationships between sonar received level and estimated probability of detecting GVPs.
